---
repositories:
  - { repo: 'deb http://www.rabbitmq.com/debian/ testing main' }

pip_install:
  - { name: 'python-software-properties' }

apt_install:
  - pkg: rabbitmq-server
    version: 3.0.2-1

apt_deinstall: []
