---
aws_ec2:
  keypair: jessedhillon-bonanza
  instance_type: t2.micro
  security_group: "{{ environment }}-worker"
  image: ami-9eaa1cf6  # ubuntu 14.04 amd64 hvm
  subnet_id: subnet-8df534d4
  instance_tags:
    - { class: worker }
    - { env: "{{ environment }}" }
  region: us-east-1
