---
sentry:
  port: 9001
  key: 4ZLwIcGZ6H0HPxLnR+VMA1%P7!G$G%JR7ieEXuLb%gJ6$4uAzKKS@!
  secret_key: l+6tOLV8Mq8QTG4rT0fn+tIGnzeY-K!@ZkH0$JUnVuB1hvPPCn0R7D

redis:
  host: "{{ ec2_public_dns_name }}"
  port: 6379

memcached:
  host: "{{ ec2_public_dns_name }}"
  port: 11211
