---
- name: copy supervisor configuration
  tags:
    - supervisor
  sudo: true
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisor/supervisord.conf
  notify:
    - restart supervisord
