"""initial schema

Revision ID: 168d2892efbe
Revises: None
Create Date: 2014-09-30 12:39:56.044237

"""

# revision identifiers, used by Alembic.
revision = '168d2892efbe'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
    sa.Column('key', sa.Ascii(length=40), nullable=False),
    sa.Column('location', sa.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('ctime', sa.UTCDateTime(), nullable=True),
    sa.Column('mtime', sa.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_listing'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing')
    ### end Alembic commands ###
