"""store_cl_source_data

Revision ID: ecc1ad2d65b
Revises: 2fba93ffd482
Create Date: 2014-10-05 23:38:36.742281

"""

# revision identifiers, used by Alembic.
revision = 'ecc1ad2d65b'
down_revision = '2fba93ffd482'

from alembic import op
import sqlalchemy as sa
import sqlalchemy.sql as sql
from batteries.model.types import Ascii, UTCDateTime
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('craigslist_listing', sa.Column('data', postgresql.JSON(), nullable=True))
    op.add_column('craigslist_listing', sa.Column('relative_url', sa.Unicode(length=200), nullable=True))
    op.add_column('craigslist_listing', sa.Column('subdomain', sa.Unicode(length=100), nullable=True))

    craigslist_listing = sql.table('craigslist_listing',
                                   sql.column('relative_url'),
                                   sql.column('subdomain'))
    url = sql.column('url')
    op.execute(craigslist_listing.update().values(relative_url=url))
    op.execute(craigslist_listing.update().values(subdomain='sfbay'))

    op.alter_column('craigslist_listing', 'relative_url', nullable=False)
    op.alter_column('craigslist_listing', 'subdomain', nullable=False)
    op.drop_column('craigslist_listing', 'url')
    op.create_index(op.f('ix_craigslist_listing_ask'), 'craigslist_listing', ['ask'], unique=False)
    op.create_index(op.f('ix_craigslist_listing_bedrooms'), 'craigslist_listing', ['bedrooms'], unique=False)
    op.create_index(op.f('ix_craigslist_listing_id'), 'craigslist_listing', ['id'], unique=False)
    op.create_index(op.f('ix_craigslist_listing_location'), 'craigslist_listing', ['location'], unique=False)
    op.create_index(op.f('ix_craigslist_listing_posted_date'), 'craigslist_listing', ['posted_date'], unique=False)
    op.drop_index('idx_craigslist_listing_location', table_name='craigslist_listing')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_craigslist_listing_location', 'craigslist_listing', ['location'], unique=False)
    op.drop_index(op.f('ix_craigslist_listing_posted_date'), table_name='craigslist_listing')
    op.drop_index(op.f('ix_craigslist_listing_location'), table_name='craigslist_listing')
    op.drop_index(op.f('ix_craigslist_listing_id'), table_name='craigslist_listing')
    op.drop_index(op.f('ix_craigslist_listing_bedrooms'), table_name='craigslist_listing')
    op.drop_index(op.f('ix_craigslist_listing_ask'), table_name='craigslist_listing')
    op.add_column('craigslist_listing', sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    craigslist_listing = sql.table('craigslist_listing',
                                   sql.column('url'),
                                   sql.column('relative_url'))
    relative_url = sql.column('relative_url')
    op.execute(craigslist_listing.update().values(url=relative_url))

    op.alter_column('craigslist_listing', 'url', nullable=False)
    op.drop_column('craigslist_listing', 'subdomain')
    op.drop_column('craigslist_listing', 'relative_url')
    op.drop_column('craigslist_listing', 'data')
    ### end Alembic commands ###
