"""update_listing_srid

Revision ID: 2fba93ffd482
Revises: 3d08656dfba2
Create Date: 2014-10-05 10:45:15.828166

"""

# revision identifiers, used by Alembic.
revision = '2fba93ffd482'
down_revision = '3d08656dfba2'

from alembic import op
from sqlalchemy.sql.functions import func
from sqlalchemy.sql.expression import select


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        select([func.UpdateGeometrySRID(
            'craigslist_listing', 'location', 4326)])
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        select([func.UpdateGeometrySRID(
            'craigslist_listing', 'location', 0)])
    )
    ### end Alembic commands ###
