---
virtualenvs:
  - "sentry"

apt_install:
  - { name: redis-server, version: "2:2.8.4-2" }
  - { name: memcached, version: 1.4.14-0ubuntu9 }

pip_user_install:
  - { name: redis, virtualenv: ~bonanza/.virtualenvs/sentry }
  - { name: hiredis, virtualenv: ~bonanza/.virtualenvs/sentry }
  - { name: nydus, virtualenv: ~bonanza/.virtualenvs/sentry }
  - { name: psycopg2, virtualenv: ~bonanza/.virtualenvs/sentry }
  - { name: sentry, virtualenv: ~bonanza/.virtualenvs/sentry }

redis:
  # host: "{{ ec2_public_dns_name }}"
  host: localhost
  port: 6379

memcached:
  # host: "{{ ec2_public_dns_name }}"
  host: localhost
  port: 11211
