---
- hosts: tag_class_monitor
  name: configure monitor instances
  tags: os
  roles:
    - supervisor
    - rabbitmq
    - sentry
  user: ubuntu
  vars_files:
    - roles/common/vars/skeleton.yml
    - roles/common/vars/packages.yml
    - roles/common/vars/credentials-vault.yml
    - roles/rabbitmq/vars/credentials-vault.yml
    - roles/sentry/vars/credentials-vault.yml
  gather_facts: true
