---
- hosts: localhost
  connection: local
  name: provision monitor
  gather_facts: false
  vars:
    aws_ec2:
      keypair: jessedhillon-bonanza
      instance_type: t2.micro
      security_group: "{{ environment }}-monitor"
      image: ami-9eaa1cf6  # ubuntu 14.04 amd64 hvm
      subnet_id: subnet-9ff452e8
      instance_tags: "class=monitor,env={{ environment }}"
      region: us-east-1
  tasks:
    - include: tasks/provision.yml
