"""add census_block

Revision ID: 59ab4b5dd0b2
Revises: 586355d5c7bb
Create Date: 2014-11-10 01:35:39.023416

"""

# revision identifiers, used by Alembic.
revision = '59ab4b5dd0b2'
down_revision = '586355d5c7bb'

from alembic import op
import sqlalchemy as sa
from batteries.model.types import Ascii, UTCDateTime
from geoalchemy2 import Geometry


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('census_block',
    sa.Column('state_fp', sa.Unicode(length=2), nullable=False),
    sa.Column('county_fp', sa.Unicode(length=3), nullable=False),
    sa.Column('tract_ce', sa.Unicode(length=6), nullable=False),
    sa.Column('block_ce', sa.Unicode(length=1), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False), nullable=True),
    sa.PrimaryKeyConstraint('state_fp', 'county_fp', 'tract_ce', 'block_ce', name=op.f('pk_census_block'))
    )
    op.create_index('ix_census_block_geometry', 'census_block', ['geometry'], unique=False, postgresql_using='gist')
    op.drop_index('idx_homepath_listing_location', table_name='homepath_listing')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_homepath_listing_location', 'homepath_listing', ['location'], unique=False)
    op.drop_index('ix_census_block_geometry', table_name='census_block')
    op.drop_table('census_block')
    ### end Alembic commands ###
