"""add homepath_listing

Revision ID: 586355d5c7bb
Revises: 1b47440b81be
Create Date: 2014-11-09 16:26:40.319428

"""

# revision identifiers, used by Alembic.
revision = '586355d5c7bb'
down_revision = '1b47440b81be'

from alembic import op
import sqlalchemy as sa
from batteries.model.types import Ascii, UTCDateTime
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepath_listing',
    sa.Column('key', Ascii(length=40), nullable=False),
    sa.Column('id', sa.Unicode(length=20), nullable=False),
    sa.Column('baths', sa.Integer(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('image_url', sa.Unicode(length=300), nullable=True),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('property_type', sa.Unicode(length=10), nullable=False),
    sa.Column('street', sa.Unicode(length=200), nullable=False),
    sa.Column('city', sa.Unicode(length=100), nullable=False),
    sa.Column('state', sa.Unicode(length=8), nullable=False),
    sa.Column('request_token', sa.Binary(), nullable=True),
    sa.Column('data', postgresql.JSON(), nullable=True),
    sa.Column('ctime', UTCDateTime(), nullable=True),
    sa.Column('mtime', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_homepath_listing'))
    )
    op.create_index(op.f('ix_homepath_listing_baths'), 'homepath_listing', ['baths'], unique=False)
    op.create_index(op.f('ix_homepath_listing_beds'), 'homepath_listing', ['beds'], unique=False)
    op.create_index(op.f('ix_homepath_listing_ctime'), 'homepath_listing', ['ctime'], unique=False)
    op.create_index(op.f('ix_homepath_listing_entry_date'), 'homepath_listing', ['entry_date'], unique=False)
    op.create_index(op.f('ix_homepath_listing_id'), 'homepath_listing', ['id'], unique=False)
    op.create_index(op.f('ix_homepath_listing_location'), 'homepath_listing', ['location'], unique=False)
    op.create_index(op.f('ix_homepath_listing_mtime'), 'homepath_listing', ['mtime'], unique=False)
    op.create_index(op.f('ix_homepath_listing_price'), 'homepath_listing', ['price'], unique=False)
    op.create_index(op.f('ix_homepath_listing_property_type'), 'homepath_listing', ['property_type'], unique=False)
    op.create_index(op.f('ix_homepath_listing_request_token'), 'homepath_listing', ['request_token'], unique=False)
    op.create_index(op.f('ix_homepath_listing_state'), 'homepath_listing', ['state'], unique=False)
    op.create_index(op.f('ix_homepath_listing_status'), 'homepath_listing', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homepath_listing_status'), table_name='homepath_listing')
    op.drop_index(op.f('ix_homepath_listing_state'), table_name='homepath_listing')
    op.drop_index(op.f('ix_homepath_listing_request_token'), table_name='homepath_listing')
    op.drop_index(op.f('ix_homepath_listing_property_type'), table_name='homepath_listing')
    op.drop_index(op.f('ix_homepath_listing_price'), table_name='homepath_listing')
    op.drop_index(op.f('ix_homepath_listing_mtime'), table_name='homepath_listing')
    op.drop_index(op.f('ix_homepath_listing_location'), table_name='homepath_listing')
    op.drop_index(op.f('ix_homepath_listing_id'), table_name='homepath_listing')
    op.drop_index(op.f('ix_homepath_listing_entry_date'), table_name='homepath_listing')
    op.drop_index(op.f('ix_homepath_listing_ctime'), table_name='homepath_listing')
    op.drop_index(op.f('ix_homepath_listing_beds'), table_name='homepath_listing')
    op.drop_index(op.f('ix_homepath_listing_baths'), table_name='homepath_listing')
    op.drop_table('homepath_listing')
    ### end Alembic commands ###
