"""census tract fks

Revision ID: 30fe7222d98f
Revises: 4bdb264edca9
Create Date: 2014-11-12 20:59:18.378972

"""

# revision identifiers, used by Alembic.
revision = '30fe7222d98f'
down_revision = '4bdb264edca9'

from alembic import op
import sqlalchemy as sa
import sqlalchemy.sql as sql
from batteries.model.types import Ascii, UTCDateTime
from geoalchemy2 import Geometry


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('craigslist_listing', sa.Column('block_ce', sa.Unicode(length=1), nullable=True))
    op.add_column('craigslist_listing', sa.Column('county_fp', sa.Unicode(length=3), nullable=True))
    op.add_column('craigslist_listing', sa.Column('state_fp', sa.Unicode(length=2), nullable=True))
    op.add_column('craigslist_listing', sa.Column('tract_ce', sa.Unicode(length=6), nullable=True))

    op.add_column('homepath_listing', sa.Column('block_ce', sa.Unicode(length=1), nullable=True))
    op.add_column('homepath_listing', sa.Column('county_fp', sa.Unicode(length=3), nullable=True))
    op.add_column('homepath_listing', sa.Column('state_fp', sa.Unicode(length=2), nullable=True))
    op.add_column('homepath_listing', sa.Column('tract_ce', sa.Unicode(length=6), nullable=True))

    census_block = sql.table('census_block', sql.column('geometry'),
                             sql.column('block_ce'), sql.column('county_fp'),
                             sql.column('state_fp'), sql.column('tract_ce'))

    homepath_listing = sql.table('homepath_listing', sql.column('id'),
                                 sql.column('location'), sql.column('block_ce'),
                                 sql.column('county_fp'), sql.column('state_fp'),
                                 sql.column('tract_ce'))

    craigslist_listing = sql.table('craigslist_listing', sql.column('id'),
                                   sql.column('location'), sql.column('block_ce'),
                                   sql.column('county_fp'), sql.column('state_fp'),
                                   sql.column('tract_ce'))

    op.execute(
        homepath_listing.update()
                        .values(tract_ce=census_block.c.tract_ce,
                                block_ce=census_block.c.block_ce,
                                county_fp=census_block.c.county_fp,
                                state_fp=census_block.c.state_fp)
                        .where(sa.func.st_within(homepath_listing.c.location,
                                                 census_block.c.geometry)))

    op.execute(
        craigslist_listing.update()
                          .values(tract_ce=census_block.c.tract_ce,
                                  block_ce=census_block.c.block_ce,
                                  county_fp=census_block.c.county_fp,
                                  state_fp=census_block.c.state_fp)
                          .where(sa.func.st_within(craigslist_listing.c.location,
                                                   census_block.c.geometry)))

    op.execute(
        craigslist_listing.delete()
                          .where(craigslist_listing.c.state_fp.is_(None))
                          .where(craigslist_listing.c.county_fp.is_(None))
                          .where(craigslist_listing.c.tract_ce.is_(None))
                          .where(craigslist_listing.c.block_ce.is_(None)))

    op.execute(
        homepath_listing.delete()
                        .where(homepath_listing.c.state_fp.is_(None))
                        .where(homepath_listing.c.county_fp.is_(None))
                        .where(homepath_listing.c.tract_ce.is_(None))
                        .where(homepath_listing.c.block_ce.is_(None)))

    op.alter_column('craigslist_listing', 'block_ce', nullable=False)
    op.alter_column('craigslist_listing', 'county_fp', nullable=False)
    op.alter_column('craigslist_listing', 'state_fp', nullable=False)
    op.alter_column('craigslist_listing', 'tract_ce', nullable=False)

    op.alter_column('homepath_listing', 'block_ce', nullable=False)
    op.alter_column('homepath_listing', 'county_fp', nullable=False)
    op.alter_column('homepath_listing', 'state_fp', nullable=False)
    op.alter_column('homepath_listing', 'tract_ce', nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homepath_listing', 'tract_ce')
    op.drop_column('homepath_listing', 'state_fp')
    op.drop_column('homepath_listing', 'county_fp')
    op.drop_column('homepath_listing', 'block_ce')
    op.drop_column('craigslist_listing', 'tract_ce')
    op.drop_column('craigslist_listing', 'state_fp')
    op.drop_column('craigslist_listing', 'county_fp')
    op.drop_column('craigslist_listing', 'block_ce')
    ### end Alembic commands ###
