"""creates craiglist listing

Revision ID: 3d08656dfba2
Revises: 168d2892efbe
Create Date: 2014-10-02 16:51:06.228153

"""

# revision identifiers, used by Alembic.
revision = '3d08656dfba2'
down_revision = '168d2892efbe'

from alembic import op
import sqlalchemy as sa
from batteries.model.types import Ascii, UTCDateTime
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('craigslist_listing',
        sa.Column('key', Ascii(length=40), nullable=False),
        sa.Column('id', sa.Unicode(length=20), nullable=False),
        sa.Column('title', sa.UnicodeText(), nullable=False),
        sa.Column('url', sa.Unicode(length=200), nullable=False),
        sa.Column('image_thumbnail_url', sa.Unicode(length=300), nullable=True),
        sa.Column('bedrooms', sa.Integer(), nullable=True),
        sa.Column('posted_date', sa.Date(), nullable=False),
        sa.Column('ask', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('location', Geometry(geometry_type='POINT'), nullable=True),
        sa.Column('ctime', UTCDateTime(), nullable=True),
        sa.Column('mtime', UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint('key', name=op.f('pk_craigslist_listing'))
    )
    op.drop_table('listing')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
        sa.Column('key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
        sa.Column('location', Geometry(geometry_type=u'POINT'), autoincrement=False, nullable=True),
        sa.Column('ctime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('mtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('key', name=u'pk_listing')
    )
    op.create_table('spatial_ref_sys',
        sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
        sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    )
    op.drop_table('craigslist_listing')
    ### end Alembic commands ###
