"""fix spatial indexing

Revision ID: 4bdb264edca9
Revises: 59ab4b5dd0b2
Create Date: 2014-11-10 01:47:07.489557

"""

# revision identifiers, used by Alembic.
revision = '4bdb264edca9'
down_revision = '59ab4b5dd0b2'

from alembic import op
import sqlalchemy as sa
from batteries.model.types import Ascii, UTCDateTime
from geoalchemy2 import Geometry


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_craigslist_listing_location', table_name='craigslist_listing')
    op.create_index('ix_craigslist_listing_location', 'craigslist_listing', ['location'], unique=False, postgresql_using='gist')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_craigslist_listing_location', table_name='craigslist_listing')
    op.create_index('idx_craigslist_listing_location', 'craigslist_listing', ['location'], unique=False)
    ### end Alembic commands ###
