"""index craigslist census block

Revision ID: 2203590c6b37
Revises: 55d65f91883b
Create Date: 2014-11-14 20:00:49.765055

"""

# revision identifiers, used by Alembic.
revision = '2203590c6b37'
down_revision = '55d65f91883b'

from alembic import op
import sqlalchemy as sa
from batteries.model.types import Ascii, UTCDateTime
from geoalchemy2 import Geometry


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_craigslist_listing_census_block', 'craigslist_listing', ['state_fp', 'county_fp', 'tract_ce', 'block_ce'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_craigslist_listing_census_block', table_name='craigslist_listing')
    ### end Alembic commands ###
