"""initial schema

Revision ID: 000000000000
Revises: None
Create Date: 2014-10-29 16:52:15.089188

"""

# revision identifiers, used by Alembic.
revision = '000000000000'
down_revision = None

from alembic import op
import sqlalchemy as sa
from batteries.model.types import Ascii, UTCDateTime
from geoalchemy2 import Geometry


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("create extension if not exists postgis")
    op.execute("create extension if not exists fuzzystrmatch")
    op.execute("create extension if not exists postgis_tiger_geocoder")
    op.execute("create extension if not exists postgis_topology")

    conn = op.get_bind()
    r = conn.execute("select 1 from pg_roles where rolname='rds_superuser'")
    if r.scalar() is not None:
        op.execute("alter schema tiger owner to rds_superuser")
        op.execute("alter schema topology owner to rds_superuser")
        op.execute("""
CREATE FUNCTION exec(text) returns text language plpgsql volatile AS $f$ BEGIN EXECUTE $1; RETURN $1; END; $f$;
SELECT exec('ALTER TABLE ' || quote_ident(s.nspname) || '.' || quote_ident(s.relname) || ' OWNER TO rds_superuser')
  FROM (
    SELECT nspname, relname
    FROM pg_class c JOIN pg_namespace n ON (c.relnamespace = n.oid) 
    WHERE nspname in ('tiger','topology') AND
    relkind IN ('r','S','v') ORDER BY relkind = 'S')
    s;""")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass
