"""record geocluster_id

Revision ID: 1337d505f5c
Revises: 56fca517b343
Create Date: 2014-11-09 00:12:57.605329

"""

# revision identifiers, used by Alembic.
revision = '1337d505f5c'
down_revision = '56fca517b343'

from alembic import op
import sqlalchemy as sa
from batteries.model.types import Ascii, UTCDateTime
from geoalchemy2 import Geometry


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_craigslist_listing_geocluster_id'), 'craigslist_listing', ['geocluster_id'], unique=False)
    op.create_index(op.f('ix_craigslist_listing_request_token'), 'craigslist_listing', ['request_token'], unique=False)
    op.create_index(op.f('ix_craigslist_listing_subdomain'), 'craigslist_listing', ['subdomain'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_craigslist_listing_subdomain'), table_name='craigslist_listing')
    op.drop_index(op.f('ix_craigslist_listing_request_token'), table_name='craigslist_listing')
    op.drop_index(op.f('ix_craigslist_listing_geocluster_id'), table_name='craigslist_listing')
    ### end Alembic commands ###
