"""record geocluster_id

Revision ID: 1b47440b81be
Revises: 56fca517b343
Create Date: 2014-11-09 00:37:34.715673

"""

# revision identifiers, used by Alembic.
revision = '1b47440b81be'
down_revision = '56fca517b343'

from alembic import op
import sqlalchemy as sa
from batteries.model.types import Ascii, UTCDateTime
from geoalchemy2 import Geometry


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('craigslist_listing', sa.Column('geocluster_id', sa.Unicode(length=20), nullable=True))
    op.add_column('craigslist_listing', sa.Column('request_token', sa.Binary(), nullable=True))
    op.create_index(op.f('ix_craigslist_listing_geocluster_id'), 'craigslist_listing', ['geocluster_id'], unique=False)
    op.create_index(op.f('ix_craigslist_listing_request_token'), 'craigslist_listing', ['request_token'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_craigslist_listing_request_token'), table_name='craigslist_listing')
    op.drop_index(op.f('ix_craigslist_listing_geocluster_id'), table_name='craigslist_listing')
    op.drop_column('craigslist_listing', 'request_token')
    op.drop_column('craigslist_listing', 'geocluster_id')
    ### end Alembic commands ###
