---
- name: install bonanza supervisor configuration
  sudo: true
  tags:
    - bonanza
    - supervisor
  copy:
    src: supervisord.conf.d/bonanza-craigslist-worker.conf
    dest: /etc/supervisor/conf.d/bonanza-craigslist-worker.conf
  notify:
    - restart supervisord
