---
- name: clone application repository
  tags:
    - bonanza
    - git
  remote_user: bonanza  # to allow SSH agent forwarding
  git: >
    repo=git@github.com:jessedhillon/bonanza.git
    dest=~/bonanza
  notify:
    - restart supervisord

- name: install bonanza configuration
  tags:
    - bonanza
    - configure
  sudo: true
  sudo_user: bonanza
  template:
    src: bonanza.ini.j2
    dest: /home/bonanza/bonanza/bonanza.ini
  notify:
    - restart supervisord

- name: enable global site packages in bonanza virtualenv
  tags:
    - bonanza
    - setuptools
  sudo: true
  sudo_user: bonanza
  file:
    path:  /home/bonanza/.virtualenvs/bonanza/lib/python2.7/no-global-site-packages.txt
    state: absent

- name: install bonanza into virtualenv
  tags: 
    - bonanza
    - setuptools
  remote_user: bonanza  # to allow SSH agent forwarding
  shell: >
    executable=/bin/bash
    source `which virtualenvwrapper.sh` && workon bonanza && pip install -e ~bonanza/bonanza/
  notify:
    - restart supervisord

- name: perform database migrations
  tags: 
    - bonanza
    - database
    - alembic
  remote_user: bonanza  # to allow SSH agent forwarding
  shell: >
    executable=/bin/bash
    source `which virtualenvwrapper.sh` && workon bonanza && cd ~bonanza/bonanza && alembic -c ~bonanza/bonanza/bonanza.ini upgrade head

- name: install bonanza fixtures
  tags:
    - bonanza
    - database
  remote_user: bonanza
  shell: >
    executable=/bin/bash
    source `which virtualenvwrapper.sh` && workon bonanza && cd ~bonanza/bonanza && populate_bonanza

- name: create bonanza log directory
  tags: 
    - bonanza
    - unix
  remote_user: bonanza
  file:
    path: /home/bonanza/bonanza/log
    state: directory
