---
- hosts: localhost
  connection: local
  name: provision worker
  gather_facts: false
  vars_files:
    - vars/main.yml
  roles:
    - ../common
  tasks:
    - include: ../common/tasks/provision.yml
