- name: enable rabbitmq plugins
  tags:
    - rabbitmq
  sudo: true
  rabbitmq_plugin:
    names: rabbitmq_management,rabbitmq_tracing,rabbitmq_federation
    state: enabled
  notify:
  - restart rabbitmq

- name: add rabbitmq user
  tags:
    - rabbitmq
  sudo: true
  rabbitmq_user:
    user: "{{ rabbitmq_user.name }}"
    password: "{{ rabbitmq_user.password }}"
    tags: administrator, "{{ rabbitmq_user.name }}"
    vhost: /
    configure_priv: .* 
    write_priv: .*
    read_priv: .*
    state: present

- name: remove rabbitmq guest user
  tags:
    - rabbitmq
  sudo: true
  rabbitmq_user:
    user: guest
    state: absent

- name: ensure rabbitmq vhost /test is present
  tags:
    - rabbitmq
  sudo: true
  rabbitmq_vhost:
    name: /test
    state: present
